name: ZIP Files

on:
  release:
    types: [published]
    
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
      with:
        files: pack.mcmeta assets/
        dest: NightingGale_server_resourcepack.zip
